name: showcase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  immich_ui:
    path: ../
  go_router: ^17.0.1
  syntax_highlight: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/themes/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: ../../../fonts/GoogleSans/GoogleSans-Regular.ttf
        - asset: ../../../fonts/GoogleSans/GoogleSans-Italic.ttf
          style: italic
        - asset: ../../../fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 500
        - asset: ../../../fonts/GoogleSans/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: ../../../fonts/GoogleSans/GoogleSans-Bold.ttf
          weight: 700
    - family: GoogleSansCode
      fonts:
        - asset: ../../../fonts/GoogleSansCode/GoogleSansCode-Regular.ttf
        - asset: ../../../fonts/GoogleSansCode/GoogleSansCode-Medium.ttf
          weight: 500
        - asset: ../../../fonts/GoogleSansCode/GoogleSansCode-SemiBold.ttf
          weight: 600