[tasks.install]
run = "pnpm install --filter immich-e2e --frozen-lockfile"

[tasks.test]
env._.path = "./node_modules/.bin"
run = "vitest --run"

[tasks."test-web"]
env._.path = "./node_modules/.bin"
run = "playwright test"

[tasks.format]
env._.path = "./node_modules/.bin"
run = "prettier --check ."

[tasks."format-fix"]
env._.path = "./node_modules/.bin"
run = "prettier --write ."

[tasks.lint]
env._.path = "./node_modules/.bin"
run = "eslint \"src/**/*.ts\" --max-warnings 0"

[tasks."lint-fix"]
run = { task = "lint --fix" }

[tasks.check]
env._.path = "./node_modules/.bin"
run = "tsc --noEmit"
