version: '3.8'

name: 'immich-test-e2e'

services:
  immich-server:
    image: immich-server-dev:latest
    build:
      context: ../../
      dockerfile: server/Dockerfile
      target: dev
    command: ['/usr/src/app/bin/immich-test', 'jobs']
    volumes:
      - /usr/src/app/node_modules
    environment:
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=e2e_test
    depends_on:
      - database

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command: -c fsync=off -c shared_preload_libraries=vectors.so
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: e2e_test
    logging:
      driver: none
