name: immich_mobile
description: Immich - selfhosted backup media file on mobile phone

publish_to: 'none'
version: 1.102.0+132

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # OS specific path
  path_provider: ^2.0.0
  path: ^1.9.0
  # Bloc
  flutter_bloc: ^8.1.5
  # Database
  drift: ^2.18.0
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  # Network
  dio: ^5.2.0
  # Route handling
  auto_route: ^8.1.0
  # Logging
  logging: ^1.2.0
  # Collection Utils
  collection: ^1.18.0
  # service_locator
  get_it: ^7.7.0
  # Photo Manager
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.1.0
  # Dynamic colors - Android
  dynamic_color: ^1.7.0
  # Material symbols
  material_symbols_icons: ^4.2719.3
  # Localization
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  # Adaptive scaffold
  flutter_adaptive_scaffold: ^0.1.10+2
  # URL launching
  url_launcher: ^6.3.0
  # plus_extensions
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  # oauth login
  flutter_web_auth_2: ^3.1.2

  openapi:
    path: openapi

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^4.0.0
  # Code generator
  build_runner: ^2.4.9
  # Database helper
  drift_dev: ^2.18.0
  # Route helper
  auto_route_generator: ^8.0.0
  # Localization generator
  slang_build_runner: ^3.30.0
  # Assets constant generator
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/utils/constants/
