name: immich_mobile
description: Immich - selfhosted backup media file on mobile phone

publish_to: 'none'
version: 1.102.0+132

environment:
  sdk: '>=3.3.3 <4.0.0'

isar_version: &isar_version 3.1.8 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Platform related
  path_provider: ^2.1.4
  path: ^1.9.0
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.0
  device_info_plus: ^11.1.0
  permission_handler: ^11.3.1
  # State handling
  flutter_bloc: ^8.1.6
  # Database
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  # Network
  http: ^1.2.2
  # Route handling
  auto_route: ^9.2.2
  # Logging
  logging: ^1.3.0
  # Collection Utils
  collection: ^1.18.0
  async: ^2.11.0
  # service_locator
  get_it: ^8.0.0
  # Photo Manager
  photo_manager: ^3.5.1
  photo_manager_image_provider: ^2.2.0
  # Localization
  intl: ^0.19.0
  slang: ^3.32.0
  slang_flutter: ^3.32.0
  # oauth login
  flutter_web_auth_2: ^4.0.1
  # components
  octo_image: ^2.1.0
  material_symbols_icons: ^4.2789.0
  flutter_adaptive_scaffold: ^0.3.1
  flutter_list_view: ^1.1.28
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  skeletonizer: ^1.4.2
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/

  openapi:
    path: openapi

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^5.0.0
  # Code generator
  build_runner: ^2.4.13
  # Database helper
  drift_dev: ^2.21.0
  # Route helper
  auto_route_generator: ^9.0.0
  # Localization generator
  slang_build_runner: ^3.32.0
  # Assets constant generator
  flutter_gen_runner: ^5.8.0
  # Type safe platform channels
  pigeon: ^22.5.0
  # Custom lint
  custom_lint: ^0.6.4
  immich_mobile_lint:
    path: './immich_lint'
  benchmarking: ^0.6.1
  faker: ^2.2.0
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/utils/constants/
