name: Build and Push Docker Image - Latest

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  # This image include both the server and microservices - the two containers can be slitted into separated
  # service with its coressponding entry file.
  build_and_push_server_monorepo_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Immich Mono Repo
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/arm/v7,linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            altran1502/immich-server:latest

  build_and_push_machine_learning_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Machine Learning
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./machine-learning
          file: ./machine-learning/Dockerfile
          platforms: linux/arm/v7,linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            altran1502/immich-machine-learning:latest

  build_and_push_web_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Web
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/arm/v7,linux/amd64,linux/arm64
          target: prod
          push: true
          tags: |
            altran1502/immich-web:latest

  build_and_push_nginx_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Proxy
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          platforms: linux/arm/v7,linux/amd64,linux/arm64
          push: true
          tags: |
            altran1502/immich-proxy:latest
